CREATE TABLE support_tickets (
  id BIGINT PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  knowledge_base_id BIGINT NOT NULL,
  created_by BIGINT NOT NULL,
  ticket_no VARCHAR(40) NOT NULL,
  status VARCHAR(32) NOT NULL,
  priority VARCHAR(32) NOT NULL,
  category VARCHAR(80) NOT NULL,
  channel VARCHAR(40) NOT NULL,
  customer_name VARCHAR(120) NOT NULL,
  customer_tier VARCHAR(40) NULL,
  customer_contact VARCHAR(160) NULL,
  order_no VARCHAR(80) NULL,
  order_status VARCHAR(80) NULL,
  product_name VARCHAR(160) NULL,
  product_sku VARCHAR(80) NULL,
  purchased_at DATETIME(6) NULL,
  issue_summary VARCHAR(300) NOT NULL,
  customer_question TEXT NOT NULL,
  latest_ai_reply TEXT NULL,
  ai_conversation_id BIGINT NULL,
  resolved_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY uk_support_tickets_tenant_no (tenant_id, ticket_no),
  KEY idx_support_tickets_tenant_status_updated (tenant_id, status, updated_at),
  KEY idx_support_tickets_kb_updated (knowledge_base_id, updated_at),
  KEY idx_support_tickets_customer (tenant_id, customer_name),
  CONSTRAINT fk_support_tickets_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_support_tickets_kb FOREIGN KEY (knowledge_base_id) REFERENCES knowledge_bases(id),
  CONSTRAINT fk_support_tickets_creator FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
