CREATE TABLE answer_feedback (
  id BIGINT PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  knowledge_base_id BIGINT NOT NULL,
  conversation_id BIGINT NOT NULL,
  user_message_id BIGINT NULL,
  assistant_message_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  rating VARCHAR(32) NOT NULL,
  reason VARCHAR(80) NULL,
  comment TEXT NULL,
  business_module VARCHAR(80) NULL,
  business_entity_id VARCHAR(120) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY uk_answer_feedback_message_user (assistant_message_id, user_id),
  KEY idx_answer_feedback_kb_created (knowledge_base_id, created_at),
  KEY idx_answer_feedback_business (business_module, business_entity_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE knowledge_issues (
  id BIGINT PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  knowledge_base_id BIGINT NOT NULL,
  conversation_id BIGINT NULL,
  user_message_id BIGINT NULL,
  assistant_message_id BIGINT NULL,
  feedback_id BIGINT NULL,
  created_by BIGINT NULL,
  source VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'OPEN',
  question TEXT NOT NULL,
  answer_summary TEXT NULL,
  reason VARCHAR(80) NULL,
  comment TEXT NULL,
  business_module VARCHAR(80) NULL,
  business_entity_id VARCHAR(120) NULL,
  resolution_note TEXT NULL,
  resolved_by BIGINT NULL,
  resolved_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  KEY idx_knowledge_issues_kb_status_created (knowledge_base_id, status, created_at),
  KEY idx_knowledge_issues_business (business_module, business_entity_id),
  KEY idx_knowledge_issues_feedback (feedback_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
